const router = require('express').Router();
const InsecureObjectRefGuard = require('../../controllers/Security/InsecureObjectRefGuard.controoler');
const { DomainValidationSchema } = require('../../helpers/Validators');
const GetFileCOntentMiddleware = require('../../middlewares/GetFileCOntentMiddleware');
const { ValidationMiddlewareQuery } = require('../../middlewares/ValidationMiddleware');
const verifyToken = require('../../middlewares/VerifyUser');
router.get('/DirectoryListingEnable',verifyToken,ValidationMiddlewareQuery(DomainValidationSchema), InsecureObjectRefGuard.DirectoryListingEnable);
router.get('/httpparameterpollution',verifyToken,ValidationMiddlewareQuery(DomainValidationSchema), InsecureObjectRefGuard.httpparameterpollution);
router.get('/robottxt',verifyToken,ValidationMiddlewareQuery(DomainValidationSchema),GetFileCOntentMiddleware, InsecureObjectRefGuard.robotsTxtPath);
module.exports = router;